name: Deploy to Firebase Hosting

on:
    push:
        branches:
            - qa # Despliega solo cuando hay cambios en la rama 'main'

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20" # Usa la versión de Node.js adecuada para tu proyecto

            - name: Install dependencies
              run: npm install

            - name: List files in src
              run: ls -R src

            - name: Build project
              run: npm run build # Este es el script de construcción que se ejecutará antes del despliegue

            - name: Deploy to Firebase
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
              run: |
                  npm install -g firebase-tools
                  firebase deploy --only hosting
